language: node_js
node_js: '10'
branches:
  only:
  - master
  - stable
services:
- mongodb
deploy:
  provider: heroku
  app: infs809
  api_key:
    secure: ZOwOF3xuMPqcv1MakPFBEFpKcQI/hbfU+9Va5qOAbaf6xYv3n/2H8NolHT3OFqhSEIKI7RPoaKlM9T36fEmXqKlGW1zM7rE0+EzHu2bfI0TmLGbsDe+PTplpfuxw8C8dRiNEIry7Lhr7I8KhCch7H7NIP8SpuyHRD5eYvz5UgRnzjroKkSLm1RVk0LO/q9kxXMGae+nO5kXGEWJz5E1rAzuS9PVEf3H+1X1Ru4SMjI3BlJ8WpcARjPY3lTb1JlAeyg7VcBUwzRDbT2LxFOUuF2eSOjaxdLyWDIHqUZ5M0uVtK+rnqcwZmKvA/zoApmxOVI8f8UFNT4OLZkOmVyevU+idqj9KZrB9spcf6dNTpd0GgWSI8nbdKmNUMA1JqS2G2V6bCdMs4d55uLuDxa3mA6DfisXQXIIOu22S3RJHAAZ9u1IHVOtwSlKi2CWuhu+4CbJU1I2BYJz/8o8n/SW9Z6N51TPFoWEU8hiWXfdtPEyTChHC2YJJOvV2XL+YV14UvhsnWgOQUhCxTZPgQscOZ3/aXLNeNIK4t9qF1pep4b9rN5Bf20DwpWh4sP7OuW7UloBC+vmVQH2+0SUu3ZHiaWSs4WUDMWzvjoP8QytyXuJVm1sMgnVH/qw5YK81rBe2etVIBXRa8I2ta2PD7zevyS4PtMiMFyR/SQZeLQIhPHY=
notifications:
  webhooks: https://outlook.office.com/webhook/4e66265c-aba7-4b5d-a2db-37956469910a@5e022ca1-5c04-4f87-8db7-d588726274e3/TravisCI/40470a8e6831401a995d2e3a6f32642d/fd2d6b9e-f6aa-404f-9abd-e45bd873c577
