language: node_js
node_js: "10"
branches:
  only:
    - master
    - stable
services:
  - mongodb
deploy:
  provider: heroku
  app: infs809
  api_key:
    secure: gr+3V4SRCLgsA51yldhHhqQYxyp/HeSCk9KcCFodjyfa3QPr3gQVN0Z9d4azo0EX4w9okLQOMim27ZddMRoa/0Kkegtf5wn4yE/8y058tqcKqvAsJ+KqihFMuAE/vVd8jKY56m5H4kEi0xeBjoMMgY5wkfNH5b/GGUKgi3Pe1l4nf3uhYc/pbu4L/gPl+/GvGFYaqqwq8h3Apq/7TcZAc6ah+MvPYwgJwnwQfxIekZSc02zxQuwPNiAQokgPWESHlEx/6phW/vpqtqrZWocahaq9E8DomdQRtyY7R04z1WTJOuJWAUwzKqsFV3UxdNvZyaS8Y3p19Tc452kWbjAbRVdygO9bJUiAO4LvM28PYutp124VpX4mUZW4Fd12BxXU+QbjuN2tTqJV6UbiTVPffS5/LKHIhOE7J20E4TiAUhjl4NqMkSOeJHiyCx1OJ+v1/HwoElfE1e/DF8iMQcHrILfFq8D9DrhKytVc/rwbWsIxLlTP+WRK6vllgqoGOk/gDwAS3eEvxDE2iytZAKbgl6WMtbou8ST6aTjVHn+TJudgfMtW8tLWeZjRH7HlHyw3VBS//ATI/CjpwSxdKq88WE4Hp+GBrBrHR+oEu7CAzxHthLRauLPg0cAqeJUGAbcdn7aDkCTvmaRourItHU5xYd6eUbpGpqtqVmT1F6lVz6c=
env:
  secure: Q1T2sBkIXreGCizA7nULY/TFEs6w16Hqpe+SgrxBLVMdYgdvogV5/F9DV7/CGeR1GHmcETGB+I/Q0qHacZ6PlTyWRR/lKcG5UQlxiNm1I46pJjy7XP7XdFKUGq6kfg+bw9+7TyyfwTk2Z4oBFT0pg/tlScSu/DD07U2b/QHKKOReBnvndsJNZtYt7u+0PlrAzg4CbP8W39gSTCcYVkhA3RNAwqp4hmfvWFmd8JK0w5icRyrCzeZm3GWYRz9mpjDWnYd+2M1poWDgUzLEEaealUmtLHaTv+/6x9O2R7eX3+xbRvfVoqPzwAT2XUHG4h5tRQGX6aPmkvoKiycLw4lmM8mPxtJt8CwgSW7BALX6P0Zrrjl+Pie8q6DzgMZKQ3yAnPYGAyvQmsvwN4K7mIBWH0bAF53mUMQ/+uLoNh17b3tYv7Niw0Eqp1/ts/f1xCYJ7TIAv3NLN0wnY5zXHPBDYi6zKRVxpRH5pgZyZ8eDNlf2pqhn+K41vrrCZ5NGO0wTE7sN6klioqfjUPvBzyeyYdaQgaE2Uuv3Iuu89LyC4JTJ8fQbzBqZzJv7utGDr6FrR6oMRD1dTrhQD2xLZk3H4YABKQ2zSQoJfphJ95ElbC1NHSC/ivT1QQf25qFMOyBaq10P82F0oPfHOYLWcI4Nrg7jyHg43kBq+ZjrAVo/eCM=
notifications:
  webhooks: https://outlook.office.com/webhook/4e66265c-aba7-4b5d-a2db-37956469910a@5e022ca1-5c04-4f87-8db7-d588726274e3/TravisCI/40470a8e6831401a995d2e3a6f32642d/fd2d6b9e-f6aa-404f-9abd-e45bd873c577
